language: java
jdk:
  -openjdk8

addons:
  sonarcloud:
    organization: "ispwrml"
    token:
      secure: 323f23294a196b1bd7e7b47fa29f14d55eb344eb



script: 
  - ant build
  - sonar-scanner