language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "ispwrml"
    token:
      secure: "a16c4fd964865f7d15bd37d9e69b68e99ab7927f" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ant build
  - sonar-scanner